// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY7AiUHJf1TExbFrHrqYbnS_3NFppiDjo',
    appId: '1:163590713345:web:b63167925dd49a63811000',
    messagingSenderId: '163590713345',
    projectId: 'chat-app-1b26a',
    authDomain: 'chat-app-1b26a.firebaseapp.com',
    storageBucket: 'chat-app-1b26a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaT5BU1Rub8euAE72Tph2OJsHg5cJayKE',
    appId: '1:163590713345:android:aee2dd2ba2f8213f811000',
    messagingSenderId: '163590713345',
    projectId: 'chat-app-1b26a',
    storageBucket: 'chat-app-1b26a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUFBPc7kMEyUGuCIJny2EGKsYxbkXWWlM',
    appId: '1:163590713345:ios:785a269f356f1b46811000',
    messagingSenderId: '163590713345',
    projectId: 'chat-app-1b26a',
    storageBucket: 'chat-app-1b26a.firebasestorage.app',
    androidClientId: '163590713345-lt062d8ss0gfstmg9o66e2a8mqodnt2q.apps.googleusercontent.com',
    iosClientId: '163590713345-cru6u1rfn65l4gsm09guq0s3olv1nubv.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

}