// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt_qJHlj-TJ08WpUpIeIJTfw4e-T0Q0F8',
    appId: '1:153785691075:web:120eab0ccf4719213beb76',
    messagingSenderId: '153785691075',
    projectId: 'genkit-recipe-app-20ad9',
    authDomain: 'genkit-recipe-app-20ad9.firebaseapp.com',
    storageBucket: 'genkit-recipe-app-20ad9.firebasestorage.app',
    measurementId: 'G-NEF0DYB72E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI9zB3_5VrReLAHVcRYqyGWy-srOz1cV4',
    appId: '1:153785691075:android:1ac965e9cd3df83f3beb76',
    messagingSenderId: '153785691075',
    projectId: 'genkit-recipe-app-20ad9',
    storageBucket: 'genkit-recipe-app-20ad9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBfVGJE9gPhkjYPr7ucnJ_GVqYgIxo_C4',
    appId: '1:153785691075:ios:9bedfb842a1ff4333beb76',
    messagingSenderId: '153785691075',
    projectId: 'genkit-recipe-app-20ad9',
    storageBucket: 'genkit-recipe-app-20ad9.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBfVGJE9gPhkjYPr7ucnJ_GVqYgIxo_C4',
    appId: '1:153785691075:ios:9bedfb842a1ff4333beb76',
    messagingSenderId: '153785691075',
    projectId: 'genkit-recipe-app-20ad9',
    storageBucket: 'genkit-recipe-app-20ad9.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt_qJHlj-TJ08WpUpIeIJTfw4e-T0Q0F8',
    appId: '1:153785691075:web:3b1fd6ae5d5226d43beb76',
    messagingSenderId: '153785691075',
    projectId: 'genkit-recipe-app-20ad9',
    authDomain: 'genkit-recipe-app-20ad9.firebaseapp.com',
    storageBucket: 'genkit-recipe-app-20ad9.firebasestorage.app',
    measurementId: 'G-2DLKTK5QCD',
  );

}